### ISSUE TITLE
Key Error on PageFreezer object instantiation

### ISSUE THREAD

**Issue by ChaiBapchya** [edgi-govdata-archiving/web-monitoring-processing#29]
Referring - [Pagefreezer_Python_module/Readme.md](edgi-govdata-archiving/web-monitoring-processing/blob/master/page_freezer_python_module/README.md)

Python script
`$ vim pagefree.py`
In Vim editor
```
from PageFreezer import PageFreezer

url_old='https://raw.githubusercontent.com/edgi-govdata-archiving/pagefreezer-cli/master/archives/falsepos-num-views-a.html'
url_new='https://raw.githubusercontent.com/edgi-govdata-archiving/pagefreezer-cli/master/archives/falsepos-num-views-b.html'
pf = PageFreezer(url_old, url_new, api_key='')
print pf.dataframe
pf.to_csv('results.csv')
print pf.full_html_changes()
print pf.diff_pairs()
```
Key Error basically indicating that the Query result unsuccessful in finding 'result'
```
Traceback (most recent call last):
  File "pagefree.py", line 5, in <module>
    pf = PageFreezer(url_old, url_new, api_key='')
  File "/home/chai/GSOC/PageFreezer.py", line 13, in __init__
    self.run_query()
  File "/home/chai/GSOC/PageFreezer.py", line 27, in run_query
    self.query_result = result.json()['result']
KeyError: 'result'
```

**Comment by ChaiBapchya** [comment]
Solved. 
Error was because the API key wasn't set. Hence, when the query was run, it couldn't find any corresponding result.
After updating it with the PageFreezer API key, the `keyerror` was resolved.
