### ISSUE TITLE
KeyError : diffs in PageFreezer output 

### ISSUE THREAD

**Issue by ChaiBapchya** [edgi-govdata-archiving/web-monitoring-processing#30]
Referring - [Pagefreezer_Python_module/Readme.md](https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/master/page_freezer_python_module/README.md)

Python script
`$ vim pagefree.py`
In Vim editor
```
from PageFreezer import PageFreezer

url_old='https://raw.githubusercontent.com/edgi-govdata-archiving/pagefreezer-cli/master/archives/falsepos-num-views-a.html'
url_new='https://raw.githubusercontent.com/edgi-govdata-archiving/pagefreezer-cli/master/archives/falsepos-num-views-b.html'
pf = PageFreezer(url_old, url_new, api_key='ABCDEFGH') #changed the API key for privacy and security
pf.dataframe
pf.to_csv('results.csv')
pf.full_html_changes()
pf.diff_pairs()
```

KeyError - indicates the query result is unable to find "diffs"

```
Traceback (most recent call last):
  File "pagefree.py", line 5, in <module>
    pf = PageFreezer(url_old, url_new, api_key)
  File "/home/chai/GSOC/PageFreezer.py", line 14, in __init__
    self.parse_to_df()
  File "/home/chai/GSOC/PageFreezer.py", line 35, in parse_to_df
    for diff in self.query_result['output']['diffs']:
KeyError: 'diffs'
```

**Comment by ChaiBapchya** [comment]
Constructor of PageFreezer class i.e. `__init__ ` calls method `parse_to_df`
```
def __init__(self,url_1, url_2, api_key):
        self.api_key = api_key
        self.url_1 = url_1
        self.url_2 = url_2
        self.run_query()
        self.parse_to_df()
```

Error is in the method `parse_to_df`
I tried to dig further - 

`print self.query_result['output']`

Output - 
```
{u'http_header_doc1': [{u'Content-Length': u'15', u'X-XSS-Protection': u'1; mode=block', u'Content-Security-Policy': u"default-src 'none'; style-src 'unsafe-inline'", u'X-Content-Type-Options': u'nosniff', u'X-Cache': u'MISS', u'X-GitHub-Request-Id': u'80DA:2C988:19579F:1A5B84:58DBF673', u'Accept-Ranges': u'bytes', u'X-Timer': u'S1490810484.076755,VS0,VE114', u'Vary': u'Authorization,Accept-Encoding', u'X-Served-By': u'cache-sea1048-SEA', u'Connection': u'keep-alive', u'X-Fastly-Request-ID': u'00da2959eb5c9fed37681cc6a80762ec32daf540', u'X-Cache-Hits': u'0', u'Strict-Transport-Security': u'max-age=31536000', u'Via': u'1.1 varnish', u'Date': u'Wed, 29 Mar 2017 18:01:24 GMT', u'Source-Age': u'0', u'X-Frame-Options': u'deny', u'Expires': u'Wed, 29 Mar 2017 18:06:24 GMT', u'Access-Control-Allow-Origin': u'*'}], u'http_history_doc2': [u'(https://raw.githubusercontent.com/edgi-govdata-archiving/pagefreezer-cli/master/archives/falsepos-num-views-b.html) Unallowed HTTP Return Code (Only 200, 301, 302, 304): 404'], u'http_history_doc1': [u'(https://raw.githubusercontent.com/edgi-govdata-archiving/pagefreezer-cli/master/archives/falsepos-num-views-a.html) Unallowed HTTP Return Code (Only 200, 301, 302, 304): 404'], u'http_header_doc2': [{u'Content-Length': u'15', u'X-XSS-Protection': u'1; mode=block', u'Content-Security-Policy': u"default-src 'none'; style-src 'unsafe-inline'", u'X-Content-Type-Options': u'nosniff', u'X-Cache': u'MISS', u'X-GitHub-Request-Id': u'6B6C:01C7:234C90:249C9A:58DBF673', u'Accept-Ranges': u'bytes', u'X-Timer': u'S1490810484.412898,VS0,VE123', u'Vary': u'Authorization,Accept-Encoding', u'X-Served-By': u'cache-sea1038-SEA', u'Connection': u'keep-alive', u'X-Fastly-Request-ID': u'fafda4261349ef774f2737ab93902300913ebc72', u'X-Cache-Hits': u'0', u'Strict-Transport-Security': u'max-age=31536000', u'Via': u'1.1 varnish', u'Date': u'Wed, 29 Mar 2017 18:01:24 GMT', u'Source-Age': u'0', u'X-Frame-Options': u'deny', u'Expires': u'Wed, 29 Mar 2017 18:06:24 GMT', u'Access-Control-Allow-Origin': u'*'}], u'http_return_code_doc1': 404, u'http_return_code_doc2': 404}
```


Basically indicates, **HTTP 404 error.**
Hence, some issue with

Diff compare **POST** request to PageFreezer (using the 2 given URLs)

**Comment by ChaiBapchya** [comment]
By substituting the sample urls with these,
url_old='https://www.w3.org/WAI/demos/bad/before/home.html'
url_new='https://www.w3.org/WAI/demos/bad/after/home.html'

I do get an output - 
('Delta Score: ', 0.3505731564220598, ' Number of changes: ', 21)
state
Change      20
Addition     1
Followed by details of the change

So basically, sample URL seems to be at fault

**Comment by danielballan** [comment]
@ChaiBapchya Yes, that URL (raw.githubusercontent....) is not one crawled by PageFreezer. To process it anyway, you can upload the text of the HTML itself instead of the URL. Does that answer your question?

**Comment by ChaiBapchya** [comment]
Yep, alright. @danielballan So, I'll edit the doc accordingly so that others dont face the issue. Another PR incoming

**Comment by danielballan** [comment]
Glorious. Thanks for helping us document this better for future newcomers!

**Comment by ChaiBapchya** [comment]
Alright, now that I found the actual raw URL updating the doc accordingly.
