### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters

### ISSUE THREAD

**Issue by ChaiBapchya** [edgi-govdata-archiving/web-monitoring-processing#32]
While converting the dataframe to CSV, 
+ in Python 2, by default it encodes as `ascii` 
+ in Python 3, by default as `utf-8`

Since, few users can use Python 2, it might throw following `UnicodeEncode error `
```
Traceback (most recent call last):
  File "pagefree.py", line 11, in <module>
    pf.to_csv('resu.csv')
  File "/home/chai/GSOC/PageFreezer.py", line 48, in to_csv
    self.dataframe.to_csv(filename)
  File "/usr/lib64/python2.7/site-packages/pandas/core/frame.py", line 1381, in to_csv
    formatter.save()
  File "/usr/lib64/python2.7/site-packages/pandas/formats/format.py", line 1475, in save
    self._save()
  File "/usr/lib64/python2.7/site-packages/pandas/formats/format.py", line 1576, in _save
    self._save_chunk(start_i, end_i)
  File "/usr/lib64/python2.7/site-packages/pandas/formats/format.py", line 1602, in _save_chunk
    lib.write_csv_rows(self.data, ix, self.nlevels, self.cols, self.writer)
  File "pandas/lib.pyx", line 1135, in pandas.lib.write_csv_rows (pandas/lib.c:20015)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2040-2041: ordinal not in range(128)
```

**Comment by ChaiBapchya** [comment]
Solution
Convert it into a dataframe and pass parameter `encoding='utf-8'` to to_csv() 
According to - [Official Pandas documentation](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html)

Hence, 
```
pf = PageFreezer(url_old, url_new, api_key) 
df = pf.dataframe                         #convert to Pandas dataframe
pf.to_csv('result.csv', encoding='utf-8') #encode it using utf-8 and then convert to csv
```

**Comment by linehammer** [comment]
To delimit by a tab you can use the sep argument of [to_csv](http://net-informations.com/ds/pd/tocsv.htm) :

`df.to_csv(file_name, sep='\t')`

To use a specific encoding (e.g. 'utf-8') use the encoding argument:

`df.to_csv(file_name, sep='\t', encoding='utf-8')`
