### ISSUE TITLE
Exception handling for DB

### ISSUE THREAD

**Issue by KrzysztofMadejski** [edgi-govdata-archiving/web-monitoring-processing#57]
I've tried importing data from IA and got an error:
```
wm import ia envirodatagov.org --site edgi --agency edgi
importing: 31 versions [01:13,  2.51s/ versions]
Traceback (most recent call last):
  File "/home/kmadejski/.virtualenvs/wm-processing/bin/wm", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/kmadejski/Projects/web-monitoring-processing/scripts/wm", line 6, in <module>
    main()
  File "/home/kmadejski/Projects/web-monitoring-processing/web_monitoring/cli.py", line 99, in main
    site=arguments['<site>'])
  File "/home/kmadejski/Projects/web-monitoring-processing/web_monitoring/cli.py", line 28, in import_ia
    return post_versions_batched(versions)
  File "/home/kmadejski/Projects/web-monitoring-processing/web_monitoring/cli.py", line 51, in post_versions_batched
    assert res.ok
AssertionError
```

It turned out to be the [wrong password](https://github.com/edgi-govdata-archiving/web-monitoring-db/issues/78), but a better error reporting than `assert res.ok` would help a lot in debugging such issues. 

How about creating APIError base classes and subclassing that based on the error received from db, as well as having general error handling (kind of middleware) in https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/master/web_monitoring/db.py

**Comment by Mr0grog** [comment]
@danielballan I feel like we mainly solved this with [`_process_errors()`](https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/master/web_monitoring/db.py#L28-L38) in the new DB API class. Should we close it?

@KrzysztofMadejski I know it’s been a while, but if you see this, do you feel like this has improved?

**Comment by danielballan** [comment]
Yes. @KrzysztofMadejski please re-open if you find time to test this and think we can do more. Thanks!

**Comment by KrzysztofMadejski** [comment]
I trust you on this! :)
